In [1]:
import torch

In [2]:
import numpy as np

In [3]:
torch.__version__


'1.1.0'

In [4]:
arr = np.array([1,2,3,4])


In [5]:
type(arr)

numpy.ndarray

In [7]:
x=torch.from_numpy(arr)

In [8]:
y=torch.as_tensor(arr)

In [9]:
y

tensor([1, 2, 3, 4])

In [10]:
x.dtype

torch.int64

In [11]:
y.dtype

torch.int64

In [15]:
arr2d =np.arange(0.0,12.0)

In [16]:
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [17]:
arr2d.reshape(4,3)

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [18]:
z = torch.as_tensor(arr2d)

In [19]:
z

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       dtype=torch.float64)

In [20]:
my_arr = np.arange(10,20)

In [21]:
my_arr = torch.tensor(my_arr)

In [22]:
my_arr

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])